name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-github:
    name: Publish to GitHub Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@raicampos"

      - name: Atualizar npm
        run: npm install -g npm@11.16.0

      - name: Instalar Dependências
        run: npm ci

      - name: Compilação (Build Artifacts)
        run: npm run build

      - name: Deploy para GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --registry=https://npm.pkg.github.com --ignore-scripts
